In [2]:
import numpy as np

In [4]:
np.random.randn(10)

array([ 1.10501503,  0.77440434,  0.7629351 ,  1.59694137,  0.32286894,
       -0.26138333, -0.7185563 , -1.8946549 , -0.95320048,  0.18411165])

In [11]:
np.random.randint(10, size = 20).reshape(4,5)

array([[1, 2, 1, 4, 2],
       [0, 6, 3, 5, 6],
       [6, 5, 8, 2, 8],
       [7, 4, 3, 5, 7]])

In [ ]:
#Array Operation-------------------------------------------

In [18]:
a = np.random.randint(10, size = 20).reshape(4,5)
b = np.random.randint(10, size = 20).reshape(4,5)

In [19]:
a

array([[7, 3, 0, 6, 9],
       [4, 3, 3, 3, 1],
       [3, 1, 8, 5, 3],
       [4, 0, 3, 6, 9]])

In [20]:
b

array([[0, 6, 6, 6, 5],
       [3, 4, 4, 2, 1],
       [2, 3, 8, 8, 6],
       [5, 5, 4, 1, 6]])

In [21]:
a + b

array([[ 7,  9,  6, 12, 14],
       [ 7,  7,  7,  5,  2],
       [ 5,  4, 16, 13,  9],
       [ 9,  5,  7,  7, 15]])

In [24]:
a * b

array([[ 0, 18,  0, 36, 45],
       [12, 12, 12,  6,  1],
       [ 6,  3, 64, 40, 18],
       [20,  0, 12,  6, 54]])

In [26]:
a / b

<ipython-input-26-d8e10abd5ab6>:1: RuntimeWarning: divide by zero encountered in true_divide
  a / b


array([[       inf, 0.5       , 0.        , 1.        , 1.8       ],
       [1.33333333, 0.75      , 0.75      , 1.5       , 1.        ],
       [1.5       , 0.33333333, 1.        , 0.625     , 0.5       ],
       [0.8       , 0.        , 0.75      , 6.        , 1.5       ]])

In [28]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [30]:
a

array([[7, 3, 0, 6, 9],
       [4, 3, 3, 3, 1],
       [3, 1, 8, 5, 3],
       [4, 0, 3, 6, 9]])

In [33]:
np.mat(a)

matrix([[7, 3, 0, 6, 9],
        [4, 3, 3, 3, 1],
        [3, 1, 8, 5, 3],
        [4, 0, 3, 6, 9]])

In [34]:
#Matrix Operation-------------------------------------------

In [40]:
A = np.mat(a)
B = np.mat(b)

In [41]:
A

matrix([[7, 3, 0, 6, 9],
        [4, 3, 3, 3, 1],
        [3, 1, 8, 5, 3],
        [4, 0, 3, 6, 9]])

In [42]:
B

matrix([[0, 6, 6, 6, 5],
        [3, 4, 4, 2, 1],
        [2, 3, 8, 8, 6],
        [5, 5, 4, 1, 6]])

In [44]:
A + B

matrix([[ 7,  9,  6, 12, 14],
        [ 7,  7,  7,  5,  2],
        [ 5,  4, 16, 13,  9],
        [ 9,  5,  7,  7, 15]])

In [47]:
A * B

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [49]:
a = np.random.randint(10, size = 20).reshape(4,5)
b = np.random.randint(10, size = 20).reshape(5,4)

In [59]:
a = np.mat(a)

In [58]:
b = np.mat(b)

In [61]:
a * b

matrix([[ 55,  73, 151,  79],
        [ 43,  16,  56,  20],
        [ 87,  73, 125,  56],
        [ 55,  86, 142,  84]])

In [62]:
#Array Function-------------------------------------------

In [65]:
a = np.random.randint(10, size = 20).reshape(4, 5)
a

array([[8, 8, 2, 1, 6],
       [9, 8, 3, 3, 3],
       [7, 8, 5, 3, 4],
       [0, 2, 3, 3, 4]])

In [69]:
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
sum(a) #sum of each column

array([24, 26, 13, 10, 17])

In [74]:
sum(a[0]) # sum of the first row

25

In [76]:
sum(a[:,0]) # sum of the first column

24

In [78]:
a.max()

9