In [2]:
import numpy as np

In [12]:
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_1

[1, 2, 3, 4]

In [13]:
array_1 = np.array(list_1)
array_2 = np.array([list_1, list_2])

array_1, array_2

(array([1, 2, 3, 4]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [18]:
array_2.shape, array_2.size, array_2.dtype

((2, 4), 8, dtype('int64'))

In [20]:
array_3 = np.array([[0, 1, 2],
                   [1.1, 3, 4]])
array_3.dtype

dtype('float64')

In [22]:
array_4 = np.arange(1,10,2)
array_4

array([1, 3, 5, 7, 9])

In [24]:
np.zeros(5), np.zeros([2,3])

(array([0., 0., 0., 0., 0.]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

In [30]:
np.eye(5), np.eye(5).dtype

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 dtype('float64'))

In [32]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a[1], a[1:5]

(2, array([2, 3, 4, 5]))

In [44]:
b = np.array([[1,2,3],
            [4,5,6]])

b[0][1], b[0,1]

(2, 2)

In [48]:
b[:2, 2:]

array([[3],
       [6]])