In [2]:
import pickle
import numpy as np

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
f = open('x.pkl','wb') # write binary

In [9]:
pickle.dump(x,f) #put array x to file f

In [11]:
!ls

01-Array.ipynb                  untitled folder
01-Array_Operation.ipynb        x.pkl
01-Array_input_and_output.ipynb


In [12]:
f = open('x.pkl','rb') #read binary

In [14]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#numpy------------------------

In [22]:
np.save('one_array',x)

In [23]:
!ls

01-Array.ipynb                  one_array.npy
01-Array_Operation.ipynb        untitled folder
01-Array_input_and_output.ipynb x.pkl


In [24]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
y = np.arange(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
np.savez('two_array.npz',a=x,b=y)

In [31]:
!ls

01-Array.ipynb                  two_array.npz
01-Array_Operation.ipynb        untitled folder
01-Array_input_and_output.ipynb x.pkl
one_array.npy


In [32]:
c =np.load('two_array.npz')
c

In [35]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])